/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package torres_tp6.View;

import torres_tp6.Entidades.Directorio;

/**
 *
 * @author Jannete
 */
public class Menu extends javax.swing.JFrame {
private Directorio directorio=new Directorio();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiBuscarCli = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiAgregarCli = new javax.swing.JMenuItem();
        jmiBorrarCli = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Buscar");

        jmiBuscarCli.setText("Buscar cliente por telefono");
        jmiBuscarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBuscarCliActionPerformed(evt);
            }
        });
        jMenu1.add(jmiBuscarCli);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jmiAgregarCli.setText("agregar cliente");
        jmiAgregarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAgregarCliActionPerformed(evt);
            }
        });
        jMenu2.add(jmiAgregarCli);

        jmiBorrarCli.setText("borrar cliente");
        jmiBorrarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBorrarCliActionPerformed(evt);
            }
        });
        jMenu2.add(jmiBorrarCli);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Salir");

        jMenuItem3.setText("Salir");
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAgregarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAgregarCliActionPerformed
        // TODO add your handling code here:
       escritorio.removeAll();
       escritorio.repaint();
       viewAgregarClientes vac=new viewAgregarClientes(directorio);
       vac.setVisible(true);
       escritorio.add(vac);
       escritorio.moveToFront(vac);
    }//GEN-LAST:event_jmiAgregarCliActionPerformed

    private void jmiBuscarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBuscarCliActionPerformed
        // TODO add your handling code here:
       escritorio.removeAll();
       escritorio.repaint();
       viewBusquedaClientes vbc=new viewBusquedaClientes(directorio);
       vbc.setVisible(true);
       escritorio.add(vbc);
       escritorio.moveToFront(vbc);
    }//GEN-LAST:event_jmiBuscarCliActionPerformed

    private void jmiBorrarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBorrarCliActionPerformed
        // TODO add your handling code here:
       escritorio.removeAll();
       escritorio.repaint();
       viewBorrarClientes vbc=new viewBorrarClientes(directorio);
       vbc.setVisible(true);
       escritorio.add(vbc);
       escritorio.moveToFront(vbc);
    }//GEN-LAST:event_jmiBorrarCliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jmiAgregarCli;
    private javax.swing.JMenuItem jmiBorrarCli;
    private javax.swing.JMenuItem jmiBuscarCli;
    // End of variables declaration//GEN-END:variables
}
